Feature: DSL testing frameworks powered by Gherking and cucumber
Source code is available at https://github.com/BasHamer/PossumLabs
Articles are posted at https://PossumLabs.com 


Background:
Given this is presented by Bas Hamer
And he has builds the frameworks for companies as Possum Labs

Scenario: Introduction

Given you follow this series
When you have a need to implement a DSL for testing
Then you'll know how to do this


    